### ISSUE TITLE
Premium on pornhub

### ISSUE THREAD

**Issue by Lucas559-noob** [684102/PornDownloader#10]
With this script I can see premium videos but not in premium quality (above 1080p) but can my account be banned?
How do I change the setting (if any) to not show the video in theater mode (without showing almost the entire screen) I prefer the old way.
And what is acceptable ads?

**Comment by 684102** [comment]
- Try this one : [view_video.php?viewkey=ph5ef4370e39b02](https://www.pornhub.com/view_video.php?viewkey=ph5ef4370e39b02)
- Your account was safe,the script don't do anything with your account information , as the hacking step work on our server
- Acceptable Ads are ads that aren't intrusive or annoying. They are respectful, don't interfere with content, and are clearly labeled with the word “advertisement” or its equivalent.
