### ISSUE TITLE
Blocked video

### ISSUE THREAD

**Issue by Lucas559-noob** [684102/PornDownloader#11]
In the [link ](https://www.pornhub.com/view_video.php?viewkey=ph5ef4370e39b02)it shows that the premium content was loaded but the video is a gray player

**Expected behavior**
A non-pornhub player with a functional video and a working download button

[![Image from Gyazo](https://i.gyazo.com/006820085c7ca98c1c03428e20b99d9e.gif)](https://gyazo.com/006820085c7ca98c1c03428e20b99d9e)

**Desktop (please complete the following information):**
 - OS: windows 8.1
 - Browser Microsoft Edge
 - Version 83.0.478.56

It seems that if you go through a link it is as if the video doesn’t exist, as if it didn’t have access in my country, but it could also be some extension or antivirus interfering

**Comment by 684102** [comment]
Is this problem for one link or whole premium link ?

**Comment by 684102** [comment]
I've fixed that, please update to #20203193 [https://bit.ly/jsporn](https://bit.ly/jsporn)
