### ISSUE TITLE
Can't Download videos on xvideos.com or xhamster.com

### ISSUE THREAD

**Issue by p2795** [684102/PornDownloader#13]
Says it is available for the following sites in the description on greasyfork.org but I am not able to download from xvideos.com or xhamster.com what so ever.
1.) I am on Android 9 pie and am using the latest updated version of the script.
2.) I am using FlowAny private browser on my Android device with script monkey support built into the browser.
3.) I am however able to download videos on pornhub.com with no problems and will attach screenshots to show also.

![Screenshot_20200703-185430](https://user-images.githubusercontent.com/67808834/86500757-5f812d00-bd61-11ea-8c7b-8da7dac00fcb.png)
![Screenshot_20200703-185625](https://user-images.githubusercontent.com/67808834/86500759-6019c380-bd61-11ea-9c28-9ae8b4938c6d.png)
![Screenshot_20200703-185619](https://user-images.githubusercontent.com/67808834/86500760-60b25a00-bd61-11ea-8847-e5c9742f1bb0.png)
![Screenshot_20200703-185635](https://user-images.githubusercontent.com/67808834/86500761-614af080-bd61-11ea-89be-af2100d35721.png)
![Screenshot_20200703-191815](https://user-images.githubusercontent.com/67808834/86500841-ffd75180-bd61-11ea-9e09-752aa737042c.png)
![Screenshot_20200703-191803](https://user-images.githubusercontent.com/67808834/86500842-006fe800-bd62-11ea-976a-3b428728e2e7.png)

**Comment by p2795** [comment]
Sleazyfork.org I mean...
https://sleazyfork.org/en/scripts/398405-porn-downloader

**Comment by 684102** [comment]
On some website , this script not support for mobile version yet, you can check later. 
Currently , try to view as PC mode
Thank you.

**Comment by 684102** [comment]
i have supported xhamster on mobile.
