### ISSUE TITLE
PornDownloader has AD 

### ISSUE THREAD

**Issue by PLQin** [684102/PornDownloader#15]
### Be clear and concise in what you want and what you need to know

When you open the Pronhub video, it jumps to an advertising page

**Comment by 684102** [comment]
By using this scripts, you agree to enter into the "acceptable ads" program.
The script will display some pop-up to keep pornhub premium account work. As you see only the ads only at pornhub.

![image](https://user-images.githubusercont0ent.com/26831148/87214675-0d3f9d80-c359-11ea-8bf5-0f028fe6b319.png)

**Comment by PLQin** [comment]
It's not a pop-up , it's replace ！ @684102

**Comment by PLQin** [comment]
now the situation is that the AD is not a pop-up , the AD page replaces the current video's web page

**Comment by 684102** [comment]
Adfly pop-up have 5 minutes interval, you can use adblocker , but you maybe can't vew any premium video anymore.
