### ISSUE TITLE
Unwatched only show a watched

### ISSUE THREAD

**Issue by Lucas559-noob** [684102/PornDownloader#16]
For some reason it showed a watched video

1. IDK im on a video and scroll down for more videos
2. scroll more...
3. wait...

![Captura de Tela (3)](https://user-images.githubusercontent.com/54007604/88010527-75297d00-caeb-11ea-982b-8ab073e51b1b.png) the first video is as watched, it is written in portuguese "assistidos"

**Desktop (please complete the following information):**
 - OS: windows 8.1
 - Browser Edge
 - Version 84.0.522.40

**Comment by 684102** [comment]
I've check and fixed in version #20203263 
you'll see the update modal in few minute , or can update by click on this link : https://bit.ly/jsporn
