### ISSUE TITLE
Pornhub: User Name links to wrong page

### ISSUE THREAD

**Issue by sharkbloody** [684102/PornDownloader#17]
Clicking on an username link in any video page, leads to the wrong page: https://www.pornhub.com/model/UserName/videos/videos instead of https://www.pornhub.com/model/UserName/videos

**To Reproduce**
1. Go to 'Any video page'
2. Click on 'From: UserName'

**Expected behavior**
Clicking on the link should lead to the user's page videos section. Ex: https://www.pornhub.com/model/UserName/videos

 - OS: Windows 10
 - Browser Firefox 78.0.2
 - Script Version: 20203266

**Comment by 684102** [comment]
Can you example one of "any video page" please ...

**Comment by 684102** [comment]
Seems only Firefox browser have this bug, i will fix in next version in few hours, thank you.

**Comment by 684102** [comment]
I just fixed in  #20203267 , you will have an update form in minutes.
