### ISSUE TITLE
您好，请问9uu视频怎么下？

### ISSUE THREAD

**Issue by superyuer** [684102/PornDownloader#18]
您好，使用咱们的插件可以观看9uu视频，但是9uu视频无法下载

**Comment by 684102** [comment]
该网站使用hls将视频分割成许多短视频，您可以使用 [HDS-HLS-Video-Downloader](https://github.com/684102/HDS-HLS-Video-Downloader) 扩展下载所有这些内容，然后合并到一个文件中。

**Comment by huangbo1235** [comment]
请问在哪里观看？？
