### ISSUE TITLE
pornhub付费视频无法破解

### ISSUE THREAD

**Issue by a2449319025** [684102/PornDownloader#20]
服务器一直处于过载状态，试过好多次都是如此。显示以下状态：
![2222222222222222](https://user-images.githubusercontent.com/51658249/89560395-82639d00-d849-11ea-85bf-5f62d41647b1.png)
然后楼主之前给的网站也能连接上，与防火墙无关。想着服务器不可能一直过载吧。。。如果一直是的话，可以考虑ip限制破解次数以防止过载。
![111111111111111111](https://user-images.githubusercontent.com/51658249/89560503-aaeb9700-d849-11ea-8a0d-fb8e7ab5f7b5.png)

**Comment by 684102** [comment]
让我看看你看到问题的网址。

请检查其他扩展，如adblocker或其他用户脚本，可能有冲突
