### ISSUE TITLE
Duplicated videos

### ISSUE THREAD

**Issue by Lucas559-noob** [684102/PornDownloader#21]
**Describe the bug**
Sometimes in videos tab it show duplicated videos

**To Reproduce**
1. Go to videos page
2. Scroll down to load more videos
3. See error

**Expected behavior**
A non duplicated videos

**Screenshots**
<a href="https://gyazo.com/3d8937dab64678c300c5dd581e3d9fcd"><img src="https://i.gyazo.com/3d8937dab64678c300c5dd581e3d9fcd.png" alt="Image from Gyazo" width="1293"/></a> "Alinity abuses..." and other "Alinity abuses..." are the same video and It's not a short is duplicated too and other videos too <a href="https://gyazo.com/6523d08bfdaac399a999950fc542d5b7"><img src="https://i.gyazo.com/6523d08bfdaac399a999950fc542d5b7.png" alt="Image from Gyazo" width="1312"/></a>

**Desktop (please complete the following information):**
 - OS:  windows 8.1
 - Browser Edge(chrome)
 - Version 84.0.522.52

**Comment by 684102** [comment]
Seems pornhub only allowed to fetching 5 pages at all, when i've tried to load page 6, or page 7+, it's only return the content of page 5. 

I will fix on next update.
Thank you.
