### ISSUE TITLE
非常感谢作者，有些pornhub付费视频无法破解

### ISSUE THREAD

**Issue by varios009** [684102/PornDownloader#23]
**非常感谢作者**。
有些pornhub付费视频无法破解，希望能修复。
**下面这个就是其中一个无法破解，收费视频没有一个可以播放。其它收费的很多都正常。我已经试过 关了广告 防火墙 一样不能播。
不能播返回后，视频就显示”已观看"**
![6](https://user-images.githubusercontent.com/8581974/89998652-684e1280-dcc0-11ea-9476-c58ed51c8b35.png)

**Comment by 684102** [comment]
是坏的脚本，以便我可以提高到更好的水平，因此，您的反馈对我是非常有意义的。

你说得对，我们可以破解付费视频，但不是所有的都可以破解。此脚本允许您查看付费视频的一个条件是，您要破解的视频必须已由与我们共享的帐户购买。 每个人都可以为我们贡献或捐赠一个账户，我们将每个账户与其他账户联系起来。帮助每个使用脚本的人都可以免费访问付费内容。

我很感激你的理解，因为我对这个案子没有任何解决办法。

**Comment by varios009** [comment]
感谢对问题的回复。了解到问题，非常感谢对此脚本贡献或捐赠的每位人。
