### ISSUE TITLE
pornhub 搜索任意关键字 跳转至 Error Page Not Found

### ISSUE THREAD

**Issue by DennyGuo33669** [684102/PornDownloader#26]
pornhub 搜索任意关键字 跳转至 Error Page Not Found
点击上传者 进入主页也会有几率跳转至 Error Page Not Found

**Comment by DennyGuo33669** [comment]
比如说 在搜索框内输入 456   正常情况下应该地址栏应该是https://www.pornhub.com/video/search?search=456
但是开启PornDownloader之后 会在原有地址栏 后面加上&o=cm 变成https://www.pornhub.com/video/search?search=456&o=cm
界面显示Error Page Not Found

**Comment by 684102** [comment]
按F12打开chrome控制台，然后运行此`localStorage.clear（）;`。

**Comment by DennyGuo33669** [comment]
![image](https://user-images.githubusercontent.com/34097154/92075494-2f025180-edeb-11ea-8984-ddb6625aab07.png)

**Comment by 684102** [comment]
而已。问题解决了。
看起来问题出在功能上，可以让您记住搜索首选项。
在下一个版本之前，请勿选择以任何奇怪的值对电影进行排序.

**Comment by 684102** [comment]
> 比如说 在搜索框内输入 456 正常情况下应该地址栏应该是https://www.pornhub.com/video/search?search=456
> 但是开启PornDownloader之后 会在原有地址栏 后面自动加上&o=cm 变成https://www.pornhub.com/video/search?search=456&o=cm
> 界面显示Error Page Not Found

**此问题已在版本[20203291](https://bit.ly/jsporn)上完全修复**
