### ISSUE TITLE
Remove facebook.com & youtube.com to prevent script update prompt on these site

### ISSUE THREAD

**Issue by extrem23** [684102/PornDownloader#29]
**Describe the bug**
I think this script would not work on facebook.com & youtube.com video.
So maybe just remove it from the supported website list so it would not prompt for an update when visiting these sites.

**To Reproduce**
Just browse to youtube.com and got a "Porn Downloader update" popup

**Expected behavior**
No popup on youtube.com

**Comment by 684102** [comment]
Yep, you will never seen update pop-up on these site, also with "no porn" sites. 
although this script also remove help to remove ads from youtube and fetching link to help you easier download.

update at : #[bit.ly/jsporn](//bit.ly/jsporn)
