### ISSUE TITLE
Pornhub script don't work

### ISSUE THREAD

**Issue by Lucas559-noob** [684102/PornDownloader#33]
**Describe the bug**
The pornhub script don't do nothing on pornhub

**To Reproduce**
1. Go to pt.pornhub.com
2. See error

**Expected behavior**
The script change things

**Screenshots**
![Captura de Tela (21)](https://user-images.githubusercontent.com/54007604/93722949-e1b70b80-fb70-11ea-940f-0bfbb8bf2792.png)

**Desktop (please complete the following information):**
 - OS: windows 8.1
 - Browser: microsoft edge
 - Version: 85.0.564.51

**Comment by Lucas559-noob** [comment]
UI changed, hmmm 
![Captura de Tela (24)](https://user-images.githubusercontent.com/54007604/93726970-441f0480-fb8f-11ea-8bde-6aa81cf5610c.png)

**Comment by 684102** [comment]
do not use adblock with porndownloader

**Comment by Lucas559-noob** [comment]
the real issue was, it wasn't showing to update, now that I reinstalled, is working

**Comment by 684102** [comment]
> the real issue was, it wasn't showing to update, now that I reinstalled, is working

Glad to hear that!
