### ISSUE TITLE
Adblocking with adblock off

### ISSUE THREAD

**Issue by Lucas559-noob** [684102/PornDownloader#35]
**Describe the bug**
With adblock off it say that is blocking ads

**To Reproduce**
1. Go to a premium video
2. See error

**Expected behavior**
A screen without disable adblocker text

**Screenshots**
![Captura de Tela (25)](https://user-images.githubusercontent.com/54007604/93958595-34d5bd80-fd2d-11ea-9d03-336b62c3d475.png)
I suspect is because the other websites are with adblock on(traffic junky, google analytics)

**Desktop (please complete the following information):**
 - OS: windows 8.1
 - Browser: microsoft edge
 - Version 85.0.564.51

**Additional context**
filters used by adblock 
![Captura de Tela (26)](https://user-images.githubusercontent.com/54007604/93958873-d826d280-fd2d-11ea-9ee8-b737846635d5.png)

**Comment by 684102** [comment]
You can try to add pornhub into whitelist of adblocker.

**Comment by Lucas559-noob** [comment]
still not working
![Captura de Tela (26)](https://user-images.githubusercontent.com/54007604/94014692-439a8f80-fd82-11ea-9f27-5bb114f395be.png)

**Comment by Lucas559-noob** [comment]
ok, the problem was not the adblock, was the antivirus, the antivirus was blocking some ads and making it don't work
