### ISSUE TITLE
Filter button

### ISSUE THREAD

**Issue by Lucas559-noob** [684102/PornDownloader#36]
**Is your feature request related to a problem? Please describe.**
On the last update, was added a circle to open the filter of script, and is strange, a circle on screen

**Describe the solution you'd like**
The old way, when mouse approach the corner it will open

**Describe alternatives you've considered**
A button on top here
![Captura de Tela (28)](https://user-images.githubusercontent.com/54007604/94056375-9b51ee80-fdb4-11ea-82dc-05e95216d294.png)

**Comment by 684102** [comment]
Just made a vote , i will do it when having vote :D
