### ISSUE TITLE
Pornhub video title was hided

### ISSUE THREAD

**Issue by BandageWorm** [684102/PornDownloader#4]
I'd like to download video with the video specific title, but the download default title is the videoId. And I cannot copy/paste the real title since the title is hided by the script.

**Comment by 684102** [comment]
My script rename all title to only a word that consists of letters and associated characters, that mean chinese, thailand,russian.... language will removed.

The pornhub download link is not allowed you to save the movie as the name of movie, that can be change in the server-side only. Therefore my script can't do anything. BUT in the next version,  i will allowed you copy the original name of movie by one click, hope it can be help you to reslove the problem.

**Comment by BandageWorm** [comment]
> My script rename all title to only a word that consists of letters and associated characters, that mean chinese, thailand,russian.... language will removed.
> 
> The pornhub download link is not allowed you to save the movie as the name of movie, that can be change in the server-side only. Therefore my script can't do anything. BUT in the next version, i will allowed you copy the original name of movie by one click, hope it can be help you to reslove the problem.
> 
> you can update at https://bit.ly/porndown2

yep, lots of video titles are translated to chinese sinse i was using chinese translated PH, i understand the server link file names are numbers. all i need is a way to easily copy the title, thx.

**Comment by 684102** [comment]
> yep, lots of video titles are translated to chinese sinse i was using chinese translated PH, i understand the server link file names are numbers. all i need is a way to easily copy the title, thx.

The name is already copied whenever you click on the download button, just paste it.

**Comment by BandageWorm** [comment]
> 
> 
> > yep, lots of video titles are translated to chinese sinse i was using chinese translated PH, i understand the server link file names are numbers. all i need is a way to easily copy the title, thx.
> 
> The name is already copied whenever you click on the download button, just paste it as you want

Hi, I've tried the latest version, the click-copyied feature doesn't always work. I use latest Firefox, and I have to “right click -> save as” to rename the file before download, so i don't know how click-paste fearure works. Hope you can help me, or i have to disable this script and get an alternative, thx.

**Comment by 684102** [comment]
> > > yep, lots of video titles are translated to chinese sinse i was using chinese translated PH, i understand the server link file names are numbers. all i need is a way to easily copy the title, thx.
> > 
> > 
> > The name is already copied whenever you click on the download button, just paste it as you want
> 
> Hi, I've tried the latest version, the click-copyied feature doesn't always work. I use latest Firefox, and I have to “right click -> save as” to rename the file before download, so i don't know how click-paste fearure works. Even if I left click and cancel, then right click-> save as, most of the time I cannot paste the title. Hope you can help me, or i have to disable this script and get an alternative, thx.
> 
> left click:
> ![图片](https://user-images.githubusercontent.com/20052211/83017799-de928f80-a056-11ea-801d-8ca398ddb17e.png)
> 
> right click:
> ![图片](https://user-images.githubusercontent.com/20052211/83017848-f407b980-a056-11ea-822b-6a0917882e07.png)

Just click on that due, it automatically download with the movie named, you just configuration the download location in the firefox settings.

**Comment by BandageWorm** [comment]
> 
> 
> > > > yep, lots of video titles are translated to chinese sinse i was using chinese translated PH, i understand the server link file names are numbers. all i need is a way to easily copy the title, thx.
> > > 
> > > 
> > > The name is already copied whenever you click on the download button, just paste it as you want
> > 
> > 
> > Hi, I've tried the latest version, the click-copyied feature doesn't always work. I use latest Firefox, and I have to “right click -> save as” to rename the file before download, so i don't know how click-paste fearure works. Even if I left click and cancel, then right click-> save as, most of the time I cannot paste the title. Hope you can help me, or i have to disable this script and get an alternative, thx.
> > left click:
> > ![图片](https://user-images.githubusercontent.com/20052211/83017799-de928f80-a056-11ea-801d-8ca398ddb17e.png)
> > right click:
> > ![图片](https://user-images.githubusercontent.com/20052211/83017848-f407b980-a056-11ea-822b-6a0917882e07.png)
> 
> **Why you have to right click for what ? 🙄 Just left-click, dude, it automatically download with the movie named, you just configuration the download location in the firefox settings.**

![图片](https://user-images.githubusercontent.com/20052211/83024194-95473d80-a060-11ea-8146-5c4b81931872.png)
well,left click doesn't work.

**Comment by 684102** [comment]
> ![图片](https://user-images.githubusercontent.com/20052211/83024194-95473d80-a060-11ea-8146-5c4b81931872.png)
> well,left click doesn't work.

You must be allowed my script to work on `*.phncdn.com ` if you're now using Tampermonkey , i recommend you to use the Violentmonkey to manage user-script. 
If you have Chrome or **Chromium based browser** ( such as Microsoft Edge; Cent... ), you can try it with my script. I in'st check on firefox before.

**Comment by BandageWorm** [comment]
> 
> 
> > > > > yep, lots of video titles are translated to chinese sinse i was using chinese translated PH, i understand the server link file names are numbers. all i need is a way to easily copy the title, thx.
> > > > 
> > > > 
> > > > The name is already copied whenever you click on the download button, just paste it as you want
> > > 
> > > 
> > > Hi, I've tried the latest version, the click-copyied feature doesn't always work. I use latest Firefox, and I have to “right click -> save as” to rename the file before download, so i don't know how click-paste fearure works. Even if I left click and cancel, then right click-> save as, most of the time I cannot paste the title. Hope you can help me, or i have to disable this script and get an alternative, thx.
> > > left click:
> > > ![图片](https://user-images.githubusercontent.com/20052211/83017799-de928f80-a056-11ea-801d-8ca398ddb17e.png)
> > > right click:
> > > ![图片](https://user-images.githubusercontent.com/20052211/83017848-f407b980-a056-11ea-822b-6a0917882e07.png)
> > 
> > 
> > **Why you have to right click for what ? 🙄 Just left-click, dude, it automatically download with the movie named, you just configuration the download location in the firefox settings.**
> 
> ![图片](https://user-images.githubusercontent.com/20052211/83024194-95473d80-a060-11ea-8146-5c4b81931872.png)
> well,left click doesn't work.

![图片](https://user-images.githubusercontent.com/20052211/83028512-1fdd6c00-a064-11ea-9124-76ee9d690717.png)

Firefox, TamperMonkey, pink button, doesn't work.

**Comment by 684102** [comment]
> ![图片](https://user-images.githubusercontent.com/20052211/83024194-95473d80-a060-11ea-8146-5c4b81931872.png)
> well,left click doesn't work.

You must be allow my script to work on `*.phncdn.com ` if you're now using Tampermonkey , i recommend you to use the Violentmonkey to manage user-script. 
If you have Chrome or **Chromium based browser** ( such as Microsoft Edge; Cent browser... ), you can try it with my script that because i don't test on firefox before.
