### ISSUE TITLE
Show video titles on the page, plz

### ISSUE THREAD

**Issue by xmacix** [684102/PornDownloader#40]
As I see on pornhub.com, video titles are hidden from pages.
I think show them up will be more interesting, isn't it?
Thank you!

**Comment by 684102** [comment]
because of some video title having content of ads to another website, therefore we have a filter for string without any char from a-z0-9+.

And you right,the video will be more interest when it have the title back, in next update i'll do it.

**Comment by 684102** [comment]
> because some videos,the title having content of ads to another website, therefore we have a filter for string without any char from a-z0-9+.
> 
> And you're right,the video will be more interest when it have the title back, in next update i'll do it.

**I just release new version, update to [#20203316](https://bit.ly/jsporn)**
